services:
  - type: web
    name: wlsuite-python-api
    env: python
    repo: https://github.com/amaaruu/wlsuitepythonapi
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false

  - type: web
    name: wlsuite-java-backend
    env: docker
    plan: free
    envVars:
      - key: DB_URL
        value: "jdbc:postgresql://ep-delicate-union-amqi0je9-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require"
      - key: DB_USERNAME
        value: "neondb_owner"
      - key: DB_PASSWORD
        sync: false
      - key: PYTHON_API_URL
        value: "https://wlsuitepythonapi.onrender.com"
      - key: JWT_SECRET_KEY
        generateValue: true