spring.application.name=LandingBackend
server.port=${PORT:8080}

# --- CONEXIÓN A BASE DE DATOS ---
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- HIBERNATE / JPA ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# --- OPTIMIZACIÓN (HikariCP) ---
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1

# --- SEGURIDAD JWT ---
jwt.secret.key=TWlDbGF2ZVNlY3JldGFQYXJhRWxQcm95ZWN0bzIwMjY=

# --- INTEGRACIÓN IA (PYTHON) ---
python.api.url=${PYTHON_API_URL:http://localhost:8000/api/v1/ai/generate}